name: Deploy to server

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Deploy container
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.DEPLOY_IP}}
        username: ubuntu
        key: ${{secrets.DEPLOY_SSH_KEY}}
        script_stop: true
        script: |
          rm -rf telegram_search_bot
          git clone https://github.com/viktal/telegram_search_bot.git
          cd telegram_search_bot

          sudo docker build -t pybot:latest .
          sudo docker stop $(sudo docker ps -aq)
          sudo docker run pybot:latest & disown
          sudo docker system prune -f
