name: Workflow dispatch

on: [workflow_dispatch]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - name: Hello!
      run: |
        echo Hello!

    - uses: actions/checkout@v2
    - name: Build docker
      run: |
        docker build -t pybot .

